# Generated by Django 4.1.7 on 2023-03-27 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("des", models.TextField(max_length=1000)),
                ("image", models.FileField(default="00", upload_to="")),
                ("writer", models.CharField(max_length=50)),
                ("day", models.CharField(max_length=100)),
                ("link", models.URLField(max_length=1000)),
            ],
        ),
    ]
