# Generated by Django 4.1.7 on 2023-03-27 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_article"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="video",
            field=models.FileField(blank=True, upload_to="data"),
        ),
        migrations.AlterField(
            model_name="article",
            name="image",
            field=models.ImageField(blank=True, upload_to="data"),
        ),
    ]
