# Generated by Django 4.1.7 on 2023-03-27 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_article_video_alter_article_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="article",
            old_name="day",
            new_name="date",
        ),
    ]
