# Generated by Django 4.1.7 on 2023-03-29 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0007_myhelp"),
    ]

    operations = [
        migrations.CreateModel(
            name="mycontact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=100)),
                ("Email", models.CharField(max_length=100)),
                ("Subject", models.CharField(max_length=1000)),
                ("Message", models.TextField(max_length=1000)),
            ],
        ),
    ]
