# Generated by Django 4.1.7 on 2023-03-30 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0008_mycontact"),
    ]

    operations = [
        migrations.CreateModel(
            name="userregister",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Firstname", models.CharField(max_length=100)),
                ("Lastname", models.CharField(max_length=100)),
                ("Email", models.EmailField(max_length=100)),
                ("Password", models.CharField(max_length=100)),
                ("CPassword", models.CharField(max_length=100)),
            ],
        ),
    ]
