# Generated by Django 4.1.7 on 2023-04-03 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0009_userregister"),
    ]

    operations = [
        migrations.CreateModel(
            name="universities",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=100)),
                ("Ranking", models.CharField(max_length=100)),
                ("Location", models.EmailField(max_length=100)),
                ("EstablishedYear", models.CharField(max_length=100)),
                ("Type", models.CharField(max_length=100)),
            ],
        ),
    ]
