# Generated by Django 4.1.7 on 2023-04-03 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0010_universities"),
    ]

    operations = [
        migrations.AddField(
            model_name="universities",
            name="link",
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
