# Generated by Django 4.1.7 on 2023-04-03 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0011_universities_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="universities",
            name="Image",
            field=models.ImageField(blank=True, upload_to="data"),
        ),
    ]
