# Generated by Django 4.1.7 on 2023-04-03 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0012_universities_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="universities",
            name="Enrollment",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
