# Generated by Django 4.1.7 on 2023-04-07 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0014_courses"),
    ]

    operations = [
        migrations.AddField(
            model_name="courses",
            name="ctype",
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
