# Generated by Django 4.1.7 on 2023-04-08 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0015_courses_ctype"),
    ]

    operations = [
        migrations.AddField(
            model_name="userregister",
            name="Address",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="userregister",
            name="Age",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="userregister",
            name="Contact",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="userregister",
            name="Gender",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
