# Generated by Django 4.1.7 on 2023-04-11 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0016_userregister_address_userregister_age_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="des",
        ),
        migrations.AddField(
            model_name="article",
            name="content",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="article",
            name="title",
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
