# Generated by Django 4.1.7 on 2023-04-24 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0017_remove_article_des_article_content_article_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="countries",
            fields=[
                (
                    "Countryname",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("Image", models.ImageField(blank=True, upload_to="data")),
            ],
        ),
    ]
