# Generated by Django 4.1.7 on 2023-04-25 09:12

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0018_countries"),
    ]

    operations = [
        migrations.CreateModel(
            name="cun_details",
            fields=[
                (
                    "heading",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("des", ckeditor.fields.RichTextField()),
                (
                    "Countryname",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.countries",
                    ),
                ),
            ],
        ),
    ]
