# Generated by Django 4.1.7 on 2023-04-26 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0019_cun_details"),
    ]

    operations = [
        migrations.AddField(
            model_name="cun_details",
            name="Image",
            field=models.ImageField(blank=True, upload_to="data"),
        ),
    ]
