# Generated by Django 4.1.7 on 2023-04-27 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0020_cun_details_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="universities",
            name="Location",
            field=models.CharField(max_length=100),
        ),
    ]
