# Generated by Django 4.1.7 on 2023-04-28 18:01

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0021_alter_universities_location"),
    ]

    operations = [
        migrations.CreateModel(
            name="visa",
            fields=[
                ("Image", models.ImageField(blank=True, upload_to="data")),
                (
                    "heading",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("des", ckeditor.fields.RichTextField()),
                (
                    "Countryvisa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.countries",
                    ),
                ),
            ],
        ),
    ]
