# Generated by Django 4.1.7 on 2023-05-02 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0022_visa"),
    ]

    operations = [
        migrations.CreateModel(
            name="video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Title", models.TextField()),
                ("Video", models.FileField(blank=True, upload_to="data")),
            ],
        ),
    ]
